/**
 * Renderer-error classification for the Electron launch smoke test
 * (CG-0MUX17L47000O4CE).
 *
 * Background: Chromium reports a failed resource load in the console as the
 * URL-less text `Failed to load resource: net::ERR_FILE_NOT_FOUND`. Because
 * the console message carries no URL, a bare regex over the captured
 * `sessionErrors` cannot tell which resource failed — so a benign missing
 * `thumbnail.png` (a known pre-existing gap in the sibling game repos, which
 * ship no committed thumbnail) looks identical to a genuine missing
 * scene/audio/preload asset.
 *
 * This module correlates the two capture streams the smoke test already
 * records — `sessionErrors` (from `page.on('console')` / `page.on('pageerror')`)
 * and `failedRequests` (from `page.on('requestfailed')`) — so only errors with
 * no benign explanation, or errors tied to a non-benign resource, are treated
 * as fatal. It is deliberately free of Playwright/Electron imports so the
 * correlation can be unit-tested without launching a browser.
 */

/**
 * A failed-resource URL recognised as the known-benign missing-thumbnail gap
 * (thumbnails are generated by `scripts/generate-all-thumbnails.ts` and are
 * not committed by every game repo).
 */
export const BENIGN_REQUEST_PATTERN = /thumbnail\.png$/;

/**
 * Console/page error text that, absent a benign explanation, indicates a real
 * renderer failure. This mirrors the filter the smoke test applied before the
 * correlation was introduced.
 */
export const FATAL_CONSOLE_PATTERN =
  /failed to load|net::|not allowed to load|uncaught|is not defined/i;

/** Chromium's generic, URL-less "Failed to load resource" console text. */
const GENERIC_LOAD_ERROR_PATTERN = /failed to load resource:/i;

/** A concrete resource URL embedded in the message (a scheme followed by `://`). */
const EXPLICIT_URL_PATTERN = /[a-z][a-z0-9+.-]*:\/\//i;

/** Outcome of correlating session errors with failed resource requests. */
export interface SmokeErrorReport {
  /** Console/page errors with no benign explanation — genuine failures. */
  fatalErrors: string[];
  /** Failed resource loads that are not known-benign. */
  fatalRequests: string[];
  /** Console errors attributed to a known-benign failed resource. */
  benignErrors: string[];
  /** Failed resource loads recognised as the known-benign thumbnail gap. */
  benignRequests: string[];
}

/**
 * True when a console message is Chromium's URL-less generic failed-load
 * error — the form that cannot be tied to a specific resource by its text.
 */
function isGenericResourceLoadError(error: string): boolean {
  return (
    GENERIC_LOAD_ERROR_PATTERN.test(error.trim()) &&
    !EXPLICIT_URL_PATTERN.test(error)
  );
}

/**
 * Correlate captured console/page errors with failed resource requests.
 *
 * A URL-less generic load error is attributed to a known-benign failed
 * request (matching {@link BENIGN_REQUEST_PATTERN}) while an unaccounted-for
 * benign request remains — Chromium emits one generic console error per
 * failed load. Any error with no benign explanation, any error tied to a
 * non-benign resource, and any non-benign failed request is fatal.
 */
export function classifySmokeErrors(
  sessionErrors: readonly string[],
  failedRequests: readonly string[],
): SmokeErrorReport {
  const benignRequests = failedRequests.filter((url) =>
    BENIGN_REQUEST_PATTERN.test(url),
  );
  const fatalRequests = failedRequests.filter(
    (url) => !BENIGN_REQUEST_PATTERN.test(url),
  );

  // Each benign failed request can explain at most one URL-less console error.
  let benignBudget = benignRequests.length;
  const fatalErrors: string[] = [];
  const benignErrors: string[] = [];

  for (const error of sessionErrors) {
    if (!FATAL_CONSOLE_PATTERN.test(error)) continue;

    if (isGenericResourceLoadError(error)) {
      if (benignBudget > 0) {
        benignBudget -= 1;
        benignErrors.push(error);
      } else {
        fatalErrors.push(error);
      }
      continue;
    }

    if (benignRequests.some((url) => error.includes(url))) {
      benignErrors.push(error);
    } else {
      fatalErrors.push(error);
    }
  }

  return { fatalErrors, fatalRequests, benignErrors, benignRequests };
}

/** True when the report contains any genuine renderer failure. */
export function hasFatalSmokeErrors(report: SmokeErrorReport): boolean {
  return report.fatalErrors.length > 0 || report.fatalRequests.length > 0;
}
