/**
 * Tableau Card Engine -- Unified Entry Point
 *
 * Boots a single Phaser.Game with the GameSelectorScene as the
 * landing page.
 *
 * The game catalogue is **config-driven**: it is generated by
 * `scripts/vite-game-discovery-plugin.ts` from the preset selected via the
 * `GAMES_CONFIG` environment variable (default `core-only`). This means
 *
 * - the core-engine repo builds with no games (Gym only), and
 * - a distribution can assemble any subset of 1..n games by checking out the
 *   game repos as siblings and selecting a matching preset — with no source
 *   edits here.
 *
 * The Gym is core-owned and therefore always present.
 *
 * The catalogue is stored in the Phaser registry so that game scenes can
 * return to the selector without needing to know the catalogue themselves.
 */
import Phaser from 'phaser';
import { createCardGame } from './src/ui/createCardGame';
import { GameSelectorScene, REGISTRY_KEY_GAMES, type GameEntry } from './src/ui/GameSelectorScene';
import { steamFollowClientFromWindow } from './src/ui/steam-follow-client';
import { applySteamLocks, computeSteamLocks } from './src/ui/steam-lock';
import { GAMES, SCENES } from 'virtual:game-registry';

export { GAMES };

// ── Steam bonus locks (F4, CG-0MSMAJQQT004SDCC) ─────────────
//
// In the Electron launcher the bonus catalog + follow status decide which
// games render locked. In a plain browser there is no bridge, so every game
// stays playable (intake AC5). Any failure degrades to "no locks".
async function resolveSteamGatedGames(): Promise<GameEntry[]> {
  const client = steamFollowClientFromWindow();
  if (!client) return GAMES;
  try {
    const [status, catalog] = await Promise.all([client.getStatus(), client.getBonusCatalog()]);
    return applySteamLocks(GAMES, computeSteamLocks(GAMES, catalog, status));
  } catch {
    return GAMES;
  }
}

// In replay mode we need `preserveDrawingBuffer: true` so that
// `canvas.toDataURL()` returns real content.  Without this flag
// WebGL clears the drawing buffer after compositing each frame
// and toDataURL() returns a black image.
const isReplayMode = new URLSearchParams(window.location.search).get('mode') === 'replay';

/**
 * Boot the selector once the (optional) Steam lock state has resolved.
 *
 * Top-level await is not an option — the Vite build target is ES2020 — so the
 * async resolution is awaited inside this function and invoked with `void`.
 */
async function boot(): Promise<void> {
  const gatedGames = await resolveSteamGatedGames();

  createCardGame({
    backgroundColor: '#1a2a1a',
    // Register all discovered scenes; GameSelectorScene is first so it
    // auto-starts.
    scenes: [GameSelectorScene, ...SCENES],
    type: Phaser.CANVAS,
    render: isReplayMode ? { preserveDrawingBuffer: true } : undefined,
    callbacks: {
      preBoot: (game: Phaser.Game) => {
        // Store catalogue in registry before any scene starts,
        // so GameSelectorScene.init() can read it. Locked entries carry the
        // Steam bonus lock state (see resolveSteamGatedGames above).
        game.registry.set(REGISTRY_KEY_GAMES, gatedGames);
      },
    },
    exposeOnWindow: true,
  });
}

void boot();
