/**
 * Tableau Card Engine -- Unified Entry Point
 *
 * Boots a single Phaser.Game with the GameSelectorScene as the
 * landing page.
 *
 * The game catalogue is **config-driven**: it is generated by
 * `scripts/vite-game-discovery-plugin.ts` from the preset selected via the
 * `GAMES_CONFIG` environment variable (default `core-only`). This means
 *
 * - the core-engine repo builds with no games (Gym only), and
 * - a distribution can assemble any subset of 1..n games by checking out the
 *   game repos as siblings and selecting a matching preset — with no source
 *   edits here.
 *
 * The Gym is core-owned and therefore always present.
 *
 * The catalogue is stored in the Phaser registry so that game scenes can
 * return to the selector without needing to know the catalogue themselves.
 */
import Phaser from 'phaser';
import { createCardGame } from './src/ui/createCardGame';
import { GameSelectorScene, REGISTRY_KEY_GAMES } from './src/ui/GameSelectorScene';
import { GAMES, SCENES } from 'virtual:game-registry';

export { GAMES };

// ── Phaser boot ────────────────────────────────────────────

// In replay mode we need `preserveDrawingBuffer: true` so that
// `canvas.toDataURL()` returns real content.  Without this flag
// WebGL clears the drawing buffer after compositing each frame
// and toDataURL() returns a black image.
const isReplayMode = new URLSearchParams(window.location.search).get('mode') === 'replay';

createCardGame({
  backgroundColor: '#1a2a1a',
  // Register all discovered scenes; GameSelectorScene is first so it
  // auto-starts.
  scenes: [GameSelectorScene, ...SCENES],
  type: Phaser.CANVAS,
  render: isReplayMode ? { preserveDrawingBuffer: true } : undefined,
  callbacks: {
    preBoot: (game: Phaser.Game) => {
      // Store catalogue in registry before any scene starts,
      // so GameSelectorScene.init() can read it.
      game.registry.set(REGISTRY_KEY_GAMES, GAMES);
    },
  },
  exposeOnWindow: true,
});
