/**
 * Tableau Card Engine -- Unified Entry Point
 *
 * Boots a single Phaser.Game with the GameSelectorScene as the
 * landing page.
 *
 * The game catalogue is **config-driven**: it is generated by
 * `scripts/vite-game-discovery-plugin.ts` from the preset selected via the
 * `GAMES_CONFIG` environment variable (default `core-only`). This means
 *
 * - the core-engine repo builds with no games (Gym only), and
 * - a distribution can assemble any subset of 1..n games by checking out the
 *   game repos as siblings and selecting a matching preset — with no source
 *   edits here.
 *
 * The Gym is core-owned and therefore always present.
 *
 * The catalogue is stored in the Phaser registry so that game scenes can
 * return to the selector without needing to know the catalogue themselves.
 */
import Phaser from 'phaser';
import { createCardGame } from './src/ui/createCardGame';
import {
  GameSelectorScene,
  REGISTRY_KEY_GAMES,
  REGISTRY_KEY_INCOMPATIBLE_GAMES,
  type GameEntry,
} from './src/ui/GameSelectorScene';
import { ENGINE_VERSION } from './src/core-engine';
import {
  buildGameBootPayload,
  discoverRuntimeGames,
  readContentDirFromWindow,
} from './src/ui/game-plugin-boot';
import { steamFollowClientFromWindow } from './src/ui/steam-follow-client';
import { contentUnlockClientFromWindow } from './src/ui/content-unlock-client';
import { applySteamLocks, computeSteamLocks } from './src/ui/steam-lock';
import { GAMES, SCENES } from 'virtual:game-registry';

export { GAMES };

// ── Unified game locks (F4/F6, CG-0MSMAJQQT004SDCC / CG-0MUZGBTD1007G84S) ──
//
// In the Electron launcher the bonus catalog + follow status + generalised
// action-reward unlock state decide which games render locked. The generalised
// `contentUnlocks` records are folded into the same pure computation the
// in-game DLC gate uses, so the selector and the gate agree. In a plain browser
// there is no bridge, so every game stays playable (intake AC5). Any failure
// degrades to "no locks".
async function resolveSteamGatedGames(): Promise<GameEntry[]> {
  const client = steamFollowClientFromWindow();
  if (!client) return GAMES;
  try {
    const [status, catalog, unlockRecords] = await Promise.all([
      client.getStatus(),
      client.getBonusCatalog(),
      contentUnlockClientFromWindow().getUnlocks(),
    ]);
    const unlockedTargets = unlockRecords.map((record) => record.target);
    return applySteamLocks(GAMES, computeSteamLocks(GAMES, catalog, status, unlockedTargets));
  } catch {
    return GAMES;
  }
}

// In replay mode we need `preserveDrawingBuffer: true` so that
// `canvas.toDataURL()` returns real content.  Without this flag
// WebGL clears the drawing buffer after compositing each frame
// and toDataURL() returns a black image.
const isReplayMode = new URLSearchParams(window.location.search).get('mode') === 'replay';

/**
 * Boot the selector once the (optional) Steam lock state has resolved.
 *
 * Top-level await is not an option — the Vite build target is ES2020 — so the
 * async resolution is awaited inside this function and invoked with `void`.
 */
async function boot(): Promise<void> {
  // 1. Static catalogue, with Steam bonus locks applied. In a plain browser
  //    there is no bridge, so every game stays playable.
  const gatedGames = await resolveSteamGatedGames();

  // 2. Runtime game plugins (Electron launcher only). Without a content
  //    directory (browser / core-only build) discovery is skipped and the
  //    catalogue is exactly the static one. Any manifest/load failure has
  //    already been logged and degrades to the static catalogue.
  const pluginResult = await discoverRuntimeGames({
    contentDir: readContentDirFromWindow(),
    engineVersion: ENGINE_VERSION,
  });

  // 3. Merge static + runtime games/scenes for Phaser registration.
  const payload = buildGameBootPayload({
    staticGames: gatedGames,
    staticScenes: SCENES,
    pluginResult,
  });

  createCardGame({
    backgroundColor: '#1a2a1a',
    // Register all discovered scenes; GameSelectorScene is first so it
    // auto-starts.
    scenes: [GameSelectorScene, ...payload.scenes],
    type: Phaser.CANVAS,
    render: isReplayMode ? { preserveDrawingBuffer: true } : undefined,
    callbacks: {
      preBoot: (game: Phaser.Game) => {
        // Store the merged catalogue (and any incompatible runtime games) in
        // the registry before any scene starts, so GameSelectorScene.init()
        // can read them. Locked entries carry the Steam bonus lock state.
        game.registry.set(REGISTRY_KEY_GAMES, payload.games);
        game.registry.set(
          REGISTRY_KEY_INCOMPATIBLE_GAMES,
          payload.incompatible,
        );
      },
    },
    exposeOnWindow: true,
  });
}

void boot();
