#!/usr/bin/env bash
set -euo pipefail

# Generate Main Street ToneForge assets and a runtime synth module.
#
# Usage:
#   scripts/tf-generate-synths.sh [out-dir]
#
# Default output directory:
#   build/tf-synths

OUT_DIR="${1:-${TF_SYNTH_OUT_DIR:-build/tf-synths}}"
WAV_DIR="$OUT_DIR/wav"
METADATA_MODULE_FILE="$OUT_DIR/main-street-tf-module.mjs"
RUNTIME_SYNTH_MODULE_FILE="$OUT_DIR/main-street-runtime-synth.mjs"

mkdir -p "$WAV_DIR"

if ! command -v tf >/dev/null 2>&1; then
  echo "Error: tf CLI not found on PATH. Install ToneForge and retry." >&2
  exit 1
fi

declare -a ENTRIES=(
  "card-draw:card-draw:101"
  "card-slide:card-slide:102"
  "card-place:card-place:103"
  "card-discard:card-discard:104"
  "card-coin-collect:card-coin-collect:105"
  "ui-notification-chime:ui-notification-chime:106"
  "card-table-ambience:card-table-ambience:107"
)

echo "Generating ToneForge WAV outputs into $WAV_DIR"

for entry in "${ENTRIES[@]}"; do
  IFS=':' read -r tf_key recipe seed <<< "$entry"
  out_file="$WAV_DIR/${tf_key}.wav"
  tf generate --recipe "$recipe" --seed "$seed" --output "$out_file" --json > "$OUT_DIR/${tf_key}.json"
  echo "  ✓ $tf_key ($recipe seed=$seed)"
done

cat > "$METADATA_MODULE_FILE" <<'EOF'
/**
 * Auto-generated by scripts/tf-generate-synths.sh
 *
 * Descriptor metadata from tf CLI outputs.
 */

export const descriptors = {
  'card-draw': { recipe: 'card-draw', file: 'card-draw.wav' },
  'card-slide': { recipe: 'card-slide', file: 'card-slide.wav' },
  'card-place': { recipe: 'card-place', file: 'card-place.wav' },
  'card-discard': { recipe: 'card-discard', file: 'card-discard.wav' },
  'card-coin-collect': { recipe: 'card-coin-collect', file: 'card-coin-collect.wav' },
  'ui-notification-chime': { recipe: 'ui-notification-chime', file: 'ui-notification-chime.wav' },
  'card-table-ambience': { recipe: 'card-table-ambience', file: 'card-table-ambience.wav' },
};
EOF

cat > "$RUNTIME_SYNTH_MODULE_FILE" <<'EOF'
/**
 * Auto-generated by scripts/tf-generate-synths.sh
 *
 * Runtime on-the-fly synthesis module consumed by tfAdapter.
 * Uses Tone.js synth voices (no WAV playback wrappers).
 */

import * as Tone from 'tone';

const clamp = (n) => Math.max(0, Math.min(1, Number(n) || 0));

async function ensureStarted() {
  try {
    if (Tone.context.state !== 'running') {
      await Tone.start();
    }
  } catch {
    // ignore start errors; play() will noop on failure
  }
}

function gainNode(initialVolume = 0.6) {
  return new Tone.Gain(clamp(initialVolume)).toDestination();
}

function oneShotVoice(createSynth, trigger) {
  const output = gainNode(0.6);
  const synth = createSynth().connect(output);
  let muted = false;

  return {
    async play() {
      await ensureStarted();
      if (muted) return;
      trigger(synth);
    },
    stop() {
      try {
        synth.triggerRelease?.();
      } catch {
        // noop
      }
    },
    setVolume(v) {
      output.gain.value = clamp(v);
    },
    setMute(v) {
      muted = Boolean(v);
    },
  };
}

function ambienceVoice() {
  const output = gainNode(0.25);
  const noise = new Tone.Noise('brown').connect(output);
  let playing = false;
  let muted = false;

  return {
    async play() {
      await ensureStarted();
      if (muted || playing) return;
      noise.start();
      playing = true;
    },
    stop() {
      if (!playing) return;
      noise.stop();
      playing = false;
    },
    setVolume(v) {
      output.gain.value = clamp(v) * 0.5;
    },
    setMute(v) {
      muted = Boolean(v);
      if (muted) {
        noise.stop();
        playing = false;
      }
    },
  };
}

export const descriptors = {
  'card-draw': { runtime: 'Tone.FMSynth' },
  'card-slide': { runtime: 'Tone.NoiseSynth' },
  'card-place': { runtime: 'Tone.MembraneSynth' },
  'card-discard': { runtime: 'Tone.MetalSynth' },
  'card-coin-collect': { runtime: 'Tone.Synth' },
  'ui-notification-chime': { runtime: 'Tone.PolySynth' },
  'card-table-ambience': { runtime: 'Tone.Noise' },
};

export const factories = {
  'card-draw': () => oneShotVoice(
    () => new Tone.FMSynth({ harmonicity: 2.5, modulationIndex: 4, envelope: { attack: 0.002, decay: 0.08, sustain: 0.1, release: 0.08 } }),
    (synth) => synth.triggerAttackRelease('G5', '32n'),
  ),
  'card-slide': () => oneShotVoice(
    () => new Tone.NoiseSynth({ noise: { type: 'white' }, envelope: { attack: 0.001, decay: 0.09, sustain: 0, release: 0.03 } }),
    (synth) => synth.triggerAttackRelease('16n'),
  ),
  'card-place': () => oneShotVoice(
    () => new Tone.MembraneSynth({ pitchDecay: 0.012, octaves: 2, envelope: { attack: 0.001, decay: 0.14, sustain: 0, release: 0.05 } }),
    (synth) => synth.triggerAttackRelease('C3', '16n'),
  ),
  'card-discard': () => oneShotVoice(
    () => new Tone.MetalSynth({ frequency: 140, envelope: { attack: 0.001, decay: 0.12, release: 0.02 }, harmonicity: 4.1, modulationIndex: 18, resonance: 1200, octaves: 1.5 }),
    (synth) => synth.triggerAttackRelease('32n'),
  ),
  'card-coin-collect': () => oneShotVoice(
    () => new Tone.Synth({ oscillator: { type: 'triangle' }, envelope: { attack: 0.001, decay: 0.08, sustain: 0, release: 0.06 } }),
    (synth) => synth.triggerAttackRelease('E6', '32n'),
  ),
  'ui-notification-chime': () => oneShotVoice(
    () => new Tone.PolySynth(Tone.Synth, { oscillator: { type: 'sine' }, envelope: { attack: 0.002, decay: 0.2, sustain: 0, release: 0.15 } }),
    (synth) => synth.triggerAttackRelease(['C5', 'E5', 'G5'], '8n'),
  ),
  'card-table-ambience': () => ambienceVoice(),
};

export function getFactory(name) {
  return factories[name];
}

export const TF_RUNTIME_MODULE = {
  descriptors,
  factories,
  getFactory,
};
EOF

echo "Wrote metadata module: $METADATA_MODULE_FILE"
echo "Wrote runtime synth module: $RUNTIME_SYNTH_MODULE_FILE"
echo "Done."
