#!/usr/bin/env bash
set -euo pipefail

# Generate Main Street ToneForge assets and a small runtime module descriptor.
#
# Usage:
#   scripts/tf-generate-synths.sh [out-dir]
#
# Default output directory:
#   build/tf-synths

OUT_DIR="${1:-${TF_SYNTH_OUT_DIR:-build/tf-synths}}"
WAV_DIR="$OUT_DIR/wav"
MODULE_FILE="$OUT_DIR/main-street-tf-module.mjs"

mkdir -p "$WAV_DIR"

if ! command -v tf >/dev/null 2>&1; then
  echo "Error: tf CLI not found on PATH. Install ToneForge and retry." >&2
  exit 1
fi

declare -a ENTRIES=(
  "card-draw:card-draw:101"
  "card-slide:card-slide:102"
  "card-place:card-place:103"
  "card-discard:card-discard:104"
  "card-coin-collect:card-coin-collect:105"
  "ui-notification-chime:ui-notification-chime:106"
  "card-table-ambience:card-table-ambience:107"
)

echo "Generating ToneForge WAV outputs into $WAV_DIR"

for entry in "${ENTRIES[@]}"; do
  IFS=':' read -r tf_key recipe seed <<< "$entry"
  out_file="$WAV_DIR/${tf_key}.wav"
  tf generate --recipe "$recipe" --seed "$seed" --output "$out_file" --json > "$OUT_DIR/${tf_key}.json"
  echo "  ✓ $tf_key ($recipe seed=$seed)"
done

cat > "$MODULE_FILE" <<'EOF'
/**
 * Auto-generated by scripts/tf-generate-synths.sh
 *
 * Thin runtime module for tfAdapter consumption.
 * Contains only descriptor/factory wiring to generated WAV outputs.
 */

const audioCache = new Map();

function createHtmlAudioVoice(url) {
  let audio = audioCache.get(url);
  if (!audio) {
    audio = new Audio(url);
    audio.preload = 'auto';
    audioCache.set(url, audio);
  }

  return {
    play() {
      try {
        audio.currentTime = 0;
      } catch {
        // ignore seek errors
      }
      void audio.play();
    },
    stop() {
      audio.pause();
      try {
        audio.currentTime = 0;
      } catch {
        // ignore seek errors
      }
    },
    setVolume(volume) {
      audio.volume = Math.max(0, Math.min(1, Number(volume) || 0));
    },
    setMute(muted) {
      audio.muted = Boolean(muted);
    },
  };
}

function wavUrl(file) {
  return new URL(`./wav/${file}`, import.meta.url).href;
}

export const descriptors = {
  'card-draw': { recipe: 'card-draw', file: 'card-draw.wav' },
  'card-slide': { recipe: 'card-slide', file: 'card-slide.wav' },
  'card-place': { recipe: 'card-place', file: 'card-place.wav' },
  'card-discard': { recipe: 'card-discard', file: 'card-discard.wav' },
  'card-coin-collect': { recipe: 'card-coin-collect', file: 'card-coin-collect.wav' },
  'ui-notification-chime': { recipe: 'ui-notification-chime', file: 'ui-notification-chime.wav' },
  'card-table-ambience': { recipe: 'card-table-ambience', file: 'card-table-ambience.wav' },
};

export const factories = {
  'card-draw': () => createHtmlAudioVoice(wavUrl('card-draw.wav')),
  'card-slide': () => createHtmlAudioVoice(wavUrl('card-slide.wav')),
  'card-place': () => createHtmlAudioVoice(wavUrl('card-place.wav')),
  'card-discard': () => createHtmlAudioVoice(wavUrl('card-discard.wav')),
  'card-coin-collect': () => createHtmlAudioVoice(wavUrl('card-coin-collect.wav')),
  'ui-notification-chime': () => createHtmlAudioVoice(wavUrl('ui-notification-chime.wav')),
  'card-table-ambience': () => createHtmlAudioVoice(wavUrl('card-table-ambience.wav')),
};

export function getFactory(name) {
  return factories[name];
}
EOF

echo "Wrote runtime module: $MODULE_FILE"
echo "Done."
