#!/usr/bin/env bash
set -euo pipefail

# Capture a reproducible ToneForge output sample and emit a small JS module
# describing the generated assets. This is a spike helper for CG-0MOIY2VV200658OX.

OUT_DIR="${1:-build/tf-synths-spike}"
WAV_DIR="$OUT_DIR/wav"

mkdir -p "$WAV_DIR"

if ! command -v tf >/dev/null 2>&1; then
  echo "Error: tf CLI not found on PATH. Install ToneForge first." >&2
  exit 1
fi

echo "Using tf: $(tf version 2>/dev/null || tf --version 2>/dev/null || echo unknown)"

echo "Generating representative TF recipes..."
tf generate --recipe card-flip --seed 101 --output "$WAV_DIR/card-flip.wav" --json > "$OUT_DIR/card-flip.json"
tf generate --recipe card-place --seed 202 --output "$WAV_DIR/card-place.wav" --json > "$OUT_DIR/card-place.json"

cat > "$OUT_DIR/tf-generated-sample.mjs" <<'EOF'
/**
 * Auto-generated by scripts/tf-spike-capture.sh
 *
 * Spike-only sample module documenting one viable adapter target shape.
 * This file contains descriptors only (no synthesis code).
 */

export const tfVersion = '0.1.x';

export const tfDescriptors = {
  'card-flip': {
    recipe: 'card-flip',
    seed: 101,
    wavPath: './wav/card-flip.wav',
  },
  'card-place': {
    recipe: 'card-place',
    seed: 202,
    wavPath: './wav/card-place.wav',
  },
};

export function hasDescriptor(key) {
  return Object.prototype.hasOwnProperty.call(tfDescriptors, key);
}

export function getDescriptor(key) {
  return tfDescriptors[key] ?? null;
}
EOF

echo "Wrote:"
echo "  - $OUT_DIR/card-flip.json"
echo "  - $OUT_DIR/card-place.json"
echo "  - $OUT_DIR/tf-generated-sample.mjs"
echo "  - $WAV_DIR/*.wav"
