/**
 * One-off verification for CG-0MSMDYLV30025PDX: proves the electron-mode
 * Vite build loads correctly under the `file://` protocol (no server).
 *
 * Loads dist/index.html via file:// in headless Chromium and asserts that
 * (a) the module script resolves (no 404 / net error) and
 * (b) the Phaser Game Selector canvas boots (canvas element present).
 *
 * NOTE: standalone Chromium blocks file:// module scripts by CORS policy, so
 * we launch with --allow-file-access-from-files — this mirrors how Electron's
 * file:// loading treats same-scheme assets (verified end-to-end by the
 * Playwright-Electron smoke test in the launcher work items).
 *
 * Run: npx tsx scripts/verify-file-url-load.ts
 */
import { chromium } from 'playwright';
import path from 'path';
import { fileURLToPath } from 'url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const distIndex = path.resolve(scriptDir, '..', 'dist', 'index.html');
const fileUrl = 'file://' + distIndex;

(async () => {
  const browser = await chromium.launch({
    headless: true,
    args: ['--allow-file-access-from-files'],
  });
  try {
    const page = await browser.newPage();
    const pageErrors: string[] = [];
    const failedRequests: { url: string; error: string }[] = [];
    page.on('pageerror', err => pageErrors.push(String(err)));
    page.on('console', msg => {
      if (msg.type() === 'error') pageErrors.push(msg.text());
    });
    page.on('requestfailed', req =>
      failedRequests.push({ url: req.url(), error: req.failure()?.errorText ?? 'unknown' }),
    );

    await page.goto(fileUrl, { waitUntil: 'load', timeout: 30_000 });
    // Phaser boots async; give the selector scene a moment to create its canvas.
    await page.waitForTimeout(6_000);

    const canvasCount = await page.locator('canvas').count();
    const bodyText = (await page.textContent('body'))?.slice(0, 200) ?? '';

    console.log('fileUrl:', fileUrl);
    console.log('canvasCount:', canvasCount);
    console.log('pageErrors:', pageErrors);
    console.log('failedRequests:', JSON.stringify(failedRequests, null, 1));
    console.log('bodyText:', JSON.stringify(bodyText));

    // Known pre-existing gap: some games ship no committed thumbnail (they are
    // generated by scripts/generate-all-thumbnails.ts), so a missing
    // thumbnail.png under file:// is expected and not a base-path failure.
    const KNOWN_MISSING = /thumbnail\.png$/;
    const loadErrors = failedRequests.filter(r => !KNOWN_MISSING.test(r.url));
    if (canvasCount === 0 || loadErrors.length > 0) {
      console.error('FAIL: file:// load check did not pass');
      process.exit(1);
    }
    console.log('PASS: electron-mode build loads and boots under file://');
  } finally {
    await browser.close();
  }
})();
