/// <reference types="vite/client" />

/** Build-time injected version string from package.json (e.g. "0.1.7"). */
declare const __APP_VERSION__: string;

/**
 * Virtual module generated by `scripts/vite-game-discovery-plugin.ts`.
 *
 * The catalogue is derived from the config preset (see `configs/*.json`),
 * so this declaration must stay in sync with the plugin's
 * `renderGameRegistryModule()` output.
 */
declare module 'virtual:game-registry' {
  import type Phaser from 'phaser';
  import type { GameEntry } from './ui/GameSelectorScene';

  /** The game catalogue: Gym first, then each game in preset order. */
  export const GAMES: GameEntry[];

  /** Every Phaser scene class to register (Gym scenes included). */
  export const SCENES: Array<typeof Phaser.Scene>;
}
